[project]
name = "octopus"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "httpx",
    "python-dotenv",
]

[dependency-groups]
dev = [
    "numpy>=2.4.2",
    "pandas>=3.0.0",
    "ruff",
]

[tool.ruff]
target-version = "py314"
